//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProject
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectImageUrl { get; set; }
        public Nullable<int> ProjectCategory { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
    }
}
